[package]
name = "suzz"
version = "0.1.0"
edition = "2021"
authors = ["dvnc0"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.1"
colorful = "0.2.2"
curl = "0.4.44"
